name: Preview Documentation

on:
  pull_request:
  workflow_dispatch:

jobs:
  Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pwsh ci/generate-documentation.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: docs_${{ inputs.pull-request-id }}
          path: gh-pages/*
          if-no-files-found: ignore
          include-hidden-files: true
